config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resource :dashboard, only: [:show ]

  resources :products, only: [ :new, :create, :show ] do # Route para product -> new create listing
    resources :listings, only: [ :new, :create ]
  end

  get '/stylesheet', to: 'pages#stylesheet'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :listings, only: [ :index, :show, :update] do
    resources :purchases, only: [ :new, :create ]
    resources :discounts, only: [:new, :create]
  end

  resources :purchases, only: [ :show ] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/shared/_banner-green.html.erb
<div class="banner-green" >
  <div class="banner-elements-conteiner">
    <h1>Browse through thousands of our sustainable products. Only for you.</h1>
    <p>Access all discountes becoming a <strong>premium member</strong> of BeeTooGreen</p>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <%= image_tag 'background-yellow-square.png', class: "banner-bg"  %>
  <h1 class="banner-title text-center">Buy <span class="text-gradient animated-underline">sustainable</span> products <br> at low prices</h1>
  <div class="d-flex justify-content-center mb-4"><%= link_to "Discover products", listings_path, class: "btn-gradient" %></div>
  <div class="images-container row container mx-auto">
    <div class="left-container col-3">
      <p>We want to promote a sustainable economy and create the largest sustainable shopping community</p>
      <%= image_tag 'collective-buy.png', class: "h-50 w-100" %>
    </div>
    <div class="right-container col-9 h-100">
      <div class="top-images pb-4 d-flex">
        <%= image_tag 'plastic-free-cotton.jpg', class: "w-50 h-auto" %>
        <div class="top-images-right-content pl-4">
          <p>Product certify by international fair <br> trade standars (FLO)</p>
          <div class="d-flex top-images-right">
            <%= image_tag 'eco-house.png', class: "h-100 " %>
            <%= image_tag 'eco-products.jpg', class: "h-100 " %>
           </div>
         </div>
      </div>
      <div class="bottom-images d-flex">
        <%= image_tag 'eco-soup.jpg', class: "eco-soup h-75" %>
        <%= image_tag 'eco-world.png', class: "green-world h-100 flex-grow-1 mx-5" %>
        <%= image_tag 'toothbrush.png', class: "toothbrush h-75" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_button.html.erb
 <div class="main-conteiner">
  <a href="#" class="btn-gradient">Learn more</a>
 </div>

app/views/shared/_buttons-pages.html.erb
<div class="container col-8 mt-5 mb-5">
  <a href="#" class="btn-pages-green">01</a>
  <a href="#" class="btn-pages-white">02</a>
  <a href="#" class="btn-pages-white">03</a>
  <a href="#" class="btn-pages-white">...</a>
  <a href="#"class="btn-pages-white pl-4 pr-4">Next</a>
</div>

app/views/shared/_card.html.erb
<div class="card-product">
  <div class="card-img"><img src="https://i.pinimg.com/564x/e7/65/6b/e7656b7854e08d8d8756e1f3fdd95a8e.jpg" />
    <div class="quick-view-title">
      <a href="#">Quick view</a>
    </div>
  </div>
    <div class="card-body">
      <div class="card-top-elements">
        <p>UNTIL THE 30/6/21</p>
        <p class="font-weight-bold">€ 10</p>
      </div>
      <div class="product-info">
        <h5 class="mb-3"><strong>PRODUCT NAME</strong></h5>
        <h6>This Hydrophil bamboo toothbrush is the best option to take care of your teeth while taking care of the environment.</h6>
      </div>
      <div class="card-bottom-elements">
        <a href="#">Join collective buy</a>
        <div>
          <a href="#">Read more</a>
          <i class="fas fa-arrow-right"></i>
        </div>
      </div>
    </div>
</div>

app/views/shared/_carousel.html.erb
<h2 class="text-center mb-5">Some of our favourite products</h2>

<div class="glide mb-5" data-controller="glide">
  <div class="glide__track" data-glide-el="track">
    <ul class="glide__slides">


          <% @listings.each do |listing| %>

            <li class="glide__slide">
              <div class="card-product ml-5 mb-3">
                <div class="card-img">
                  <%= link_to listing_path(listing), data: {turbolinks: false } do %>
                    <%= cl_image_tag listing.product.photos.first.key %>
                  <% end %>
                </div>
                <div class="card-body">
                  <div class="card-top-elements">
                    <p>UNTIL THE <%= listing.end_date %></p>
                    <p class="font-weight-bold"><%= listing.current_price %>€</p>
                  </div>
                  <div class="product-info">
                    <h5 class="mb-3"><strong><%= listing.product.name %></strong></h5>
                    <h6><%= listing.product.description %></h6>
                  </div>
                  <div class="card-bottom-elements">
                    <%= link_to "Join collective buy", new_listing_purchase_path(listing.id) %>
                    <div>
                      <%= link_to "Read more", listing_path(listing), data: {turbolinks: false } %>
                      <i class="fas fa-arrow-right"></i>
                    </div>
                  </div>
                </div>
              </div>

          <% end %>
          </li>


    </ul>
  </div>

  <div class="glide__arrows" data-glide-el="controls">
    <button class="glide__arrow glide__arrow--left" data-glide-dir="<"><i class="fas fa-angle-left "></i></button>
    <button class="glide__arrow glide__arrow--right" data-glide-dir=">"><i class="fas fa-angle-right"></i></button>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <footer>
    <div class="container d-flex justify-content-between footer-content">

      <div class="first-info-container">
        <p>FOLLOW US</p>
        <ul class="icons d-flex">
          <li><a href="" ><i class="fab fa-facebook"></i></a></li>
          <li><a href="" ><i class="fab fa-linkedin-in"></i></a></li>
          <li><a href="" ><i class="fab fa-instagram"></i></a></li>
          <li><a href=""><i class="fab fa-twitter"></i></a></li>
        </ul>
      </div>

      <div class="second-info-container">
        <p>INFORMATION</p>
        <div class="d-flex">
          <ul class="info">
            <li><a href="#">BeTooGreen</a></li>
            <li><a href="">Get in Touch</a></li>
            <li><a href="">Things We Like</a></li>
          </ul>
          <ul class="info">
            <li><a href="">Help Center</a></li>
            <li><a href="">Privacy Policy</a></li>
            <li><a href="">Terms of Service</a></li>
          </ul>
          <ul class="info">
            <li><a href="">We are hiring!</a></li>
            <li><a href="">Resources</a></li>
          </ul>
        </div>

      </div>

    </div>
  </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <h3 class="text-gradient navbar-btg">BeTooGreen</h3>
    <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav d-flex align-items-center">
      <% if user_signed_in? %>
        <div class="nav-link search-box p-3">
          <%= form_tag listings_path, method: :get do %>
          <button class="btn-search text-gradient" type="button"><i class="fas fa-search"></i></button>
            <%= text_field_tag :query,
              "",
              class: "input-search",
              placeholder: "Search..." %>
          <% end %>
        </div>
        <li class="nav-link text-gradient ml-1 mr-3">
          <i class="fas fa-shopping-cart" id="cart-decoration"></i>
        </li>
        <li class="nav-link dropdown p-3">
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= asset_path 'Yanik.jpg' %>" />
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Create New Product", new_product_path, class: "dropdown-item" %>
            <hr>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
         <li class="nav-link mx-1">
          <%= link_to "How it works", "#", id: "black-font" %>
        </li>
        <li>
          <i class="fas fa-circle d-flex align-items-center"></i>
        </li>
        <li class="nav-link text-gradient mx-1">
          <%= link_to "What we do", "#" %>
        </li>
        <li>
          <i class="fas fa-circle d-flex align-items-center"></i>
        </li>
        <li class="nav-link text-gradient mx-1">
          <%= link_to "Contact us", "#" %>
        </li>
        <li>
          <i class="fas fa-circle d-flex align-items-center"></i>
        </li>
        <li class="nav-link text-gradient ml-1 mr-5" id="cart-border">
          <i class="fas fa-shopping-cart"></i>
        </li>
         <li class="btn-gradient py-2">
          <%= link_to "Log In", new_user_session_path, class: "white-font" %>
        </li>

      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_reviews-stars.html.erb
<div class="container col-8 mt-5 mb-5">
  <i class="fas fa-leaf mb-4" style="color: #00997B;"></i>
  <i class="fas fa-leaf mb-4" style="color: #00997B;"></i>
  <i class="fas fa-leaf mb-4" style="color: #00997B;"></i>
  <i class="fas fa-leaf mb-4" style="color: #00997B;"></i>
  <i class="fas fa-leaf mb-4" style="color: #00997B;"></i>
</div>


<div class="container col-8 mt-5 mb-5">
  <i class="fas fa-leaf mb-4" style="color: grey;"></i>
  <i class="fas fa-leaf mb-4" style="color: grey;"></i>
  <i class="fas fa-leaf mb-4" style="color: grey;"></i>
  <i class="fas fa-leaf mb-4" style="color: grey;"></i>
  <i class="fas fa-leaf mb-4" style="color: grey;"></i>
</div>

<div class="container col-8 mt-5 mb-5">
  <i class="fas fa-leaf mb-4" style="color: #00997B;"></i>
</div>

<div class="container col-8 mt-5 mb-5">
  <i class="fas fa-leaf mb-4" style="color: grey;"></i>
</div>

app/views/shared/_search-bar.html.erb
<div class="container">
  <div class="search-underline mt-5 mb-5">
    <%= form_tag listings_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-bar",
        placeholder: "Search for your sustainable products" %>
   <% end %>
  </div>
</div>